### ISSUE TITLE
Run process to publish v642.0.0 early

### ISSUE THREAD

**Issue by calebcartwright** [alexcrichton/rustc-auto-publish#16]
hey @alexcrichton 👋 if you get a chance before Tuesday could you re-run the publish process as discussed in https://github.com/alexcrichton/rustc-auto-publish/issues/14#issuecomment-574228120?

The latset version (v641) of one of the rustc-ap* crates rustfmt uses is failing to compile on the latest nightly which I believe is because v641 is missing the changes in https://github.com/rust-lang/rust/pull/68524

**Comment by alexcrichton** [comment]
Ok should be done now!

**Comment by calebcartwright** [comment]
That did the trick, thank you so much!
