### ISSUE TITLE
Run process to publish v651.0.0 early

### ISSUE THREAD

**Issue by calebcartwright** [alexcrichton/rustc-auto-publish#20]
Sorry to have another request so quickly after the last one :smile: 

Would it be possible to trigger an early publish? I believe we're really close to finishing out this round of updates.

https://github.com/rust-lang/rustfmt/pull/4100

**Comment by alexcrichton** [comment]
Sure thing! I've pushed a commit which should trigger a publish.

**Comment by calebcartwright** [comment]
Ah sorry, I forgot GitHub Actions doesn't yet have a manual/run-now trigger. Would it be easier in the future to trigger these ad-hoc publishes if we open a PR with an empty commit?

**Comment by alexcrichton** [comment]
That works too :)
