### ISSUE TITLE
Could this publish less often?

### ISSUE THREAD

**Issue by est31** [alexcrichton/rustc-auto-publish#4]
Right now we have 134 versions already, and their numbers keep growing.

They already are inside the top ten of crates with most versions:

```
    clap (204)
    clippy (196)
    sovrin-client (159)
    serde (142)
    hyper (140)
    cargo-make (136)
    project_init (135)
    rustc-ap-serialize (134)
    rustc-ap-rustc_data_structures (133)
    rustc-ap-rustc_cratesio_shim (133)
```

Maybe publish them in a more coarse turnus, like once per week?

**Comment by tjkirch** [comment]
+1 because this is sort of unhelpful for crates.io mirrors.

**Comment by est31** [comment]
This is now the top 10 list of crates with the most releases on crates.io:

```
    rustc-ap-serialize (336)
    rustc-ap-rustc_data_structures (335)
    rustc-ap-rustc_cratesio_shim (335)
    rustc-ap-syntax_pos (332)
    rustc-ap-rustc_errors (331)
    rustc-ap-syntax (330)
    rustc-ap-rustc_target (220)
    clippy (210)
    rustc-ap-arena (206)
    clap (205)
```

**Comment by aleksmelnikov** [comment]
Could be publishing a stable version of ` rustc-ap` crates.

**Comment by alexcrichton** [comment]
Thanks for the report but with the purpose of this crate I won't be reducing the rate of publication.

**Comment by est31** [comment]
@alexcrichton what's the purpose? clippy seems to use rustc crates from the sysroot directly.

If the sole purpose is to provide support for rustfmt, it seems to not require a daily update schedule. The last 5 updates:

* [274 → 290](https://github.com/rust-lang/rustfmt/commit/9534dfc062f636ecd9bdb5d617a8d6a192e6ff27)
* [290 → 297](https://github.com/rust-lang/rustfmt/commit/f7ff0f8c89bf131fc7ccca5171c6101c83de4a7c)
* [297 → 306](https://github.com/rust-lang/rustfmt/commit/fd27eabbb7350a3b413f33728ae315be2e184825)
* [306 → 366](https://github.com/rust-lang/rustfmt/commit/f4f9502ea7b7e87e760f7f2a288829d28f213812)
* [366 → 373](https://github.com/rust-lang/rustfmt/commit/9df1ed6ab49d7e7f94edb3c0585d7d899fec0d1a)

Each time there were >= 7 days of difference. Weekly updates would be fine it seems.
