### ISSUE TITLE
rustc-ap-syntax has version 373.0.0 (Feb 13 2019) on crates.io

### ISSUE THREAD

**Issue by aleksmelnikov** [alexcrichton/rustc-auto-publish#5]
But other `rustc-ap` crates have version 385.0.0 (Feb 25 2019). May be need to repair piblishing of `rustc-ap-syntax `? Thx.

**Comment by alexcrichton** [comment]
Thanks for the ping, should be fixed now!

**Comment by aleksmelnikov** [comment]
@alexcrichton , excuse me  but it's still 373.0.0, others are 388.0.0 today.

**Comment by alexcrichton** [comment]
Oops sorry, looks like it wasn't just the cron not running but also a legit but, should be fixed now

**Comment by aleksmelnikov** [comment]
Ok Thx
