### ISSUE TITLE
What about publishing weekly?

### ISSUE THREAD

**Issue by est31** [alexcrichton/rustc-auto-publish#7]
Hi, maybe you've missed it: I haven't gotten a [reply about my inquiry on the purpose](https://github.com/alexcrichton/rustc-auto-publish/issues/4#issuecomment-467069714).

There are over 500 versions now of 11 autopublished crates. The libsyntax crate alone takes 142 MB of storage. This is not ok.

Rustfmt, the only user of this, still seems to update in a superweekly cycle, so a weekly release schedule until rustfmt adopts rust-analyzer would be okay. @topecongiro please say if you want it to stay on a daily schedule or whether a weekly release schedule would be okay, too.

Here is a list of the last three updates (earlier ones in my comment linked above):

* [373 → 407](https://github.com/rust-lang/rustfmt/commit/ce5cccc32c3897488d2c503fe9d2a9a429a9b0eb)
* [407 → 486](https://github.com/rust-lang/rustfmt/commit/2244f326e65a21b7025691478a3218d588d74f7e)
* [486 → 491](https://github.com/rust-lang/rustfmt/commit/0e3cf08ff10b099e0336b8c7a7282d7197ac3f77)

**Comment by topecongiro** [comment]
A weekly release is completely acceptable with respect to rustfmt.

**Comment by alexcrichton** [comment]
As I have mentioned before, I'm not going to change this at this time.

**Comment by est31** [comment]
@alexcrichton sorry for opening another issue but I wasn't sure whether you'd missed my last inquiry or not, as there was no reply to it. I'd still be very happy if you could outline what the precise purpose of this crate is.
